[build]
  command = "npm install && npm install tailwindcss postcss autoprefixer && npx prisma generate && npx prisma migrate deploy && SKIP_TYPE_CHECK=true next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_TYPE_CHECK = "true"

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "npm install && npm install tailwindcss postcss autoprefixer && npx prisma generate && npx prisma migrate deploy && next build"

[context.production.environment]
  NODE_ENV = "production" 