[build]
  command = "npm ci && npx prisma generate && npx prisma migrate deploy && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild" 