[build]
  command = "npm install && npm run postinstall && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild" 