[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production" 