[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_RUNTIME_CONFIG = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/engines-version"]

[build.processing]
  skip_processing = true 