[build]
  command = "next build"
  publish = ".next"

[[redirects]]
  from = "/_next/image/*"
  to = "/.netlify/images"
  query = { url = ":url", w = ":width", q = ":quality" }
  status = 200
  force = true

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/engines-version"]

[build.processing]
  skip_processing = true 